// Generated by `supabase gen types typescript` (via the Supabase MCP
// generate_typescript_types tool) against the achilla project. Do not
// hand-edit — regenerate after schema migrations change.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      custom_protocol_uploads: {
        Row: {
          confirmed_at: string | null
          created_at: string
          id: string
          original_file_path: string
          parsed_json: Json | null
          parsed_status: string
          resulting_protocol_id: string | null
          reviewed_and_edited_json: Json | null
          user_id: string
        }
        Insert: {
          confirmed_at?: string | null
          created_at?: string
          id?: string
          original_file_path: string
          parsed_json?: Json | null
          parsed_status?: string
          resulting_protocol_id?: string | null
          reviewed_and_edited_json?: Json | null
          user_id: string
        }
        Update: {
          confirmed_at?: string | null
          created_at?: string
          id?: string
          original_file_path?: string
          parsed_json?: Json | null
          parsed_status?: string
          resulting_protocol_id?: string | null
          reviewed_and_edited_json?: Json | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "custom_protocol_uploads_resulting_protocol_id_fkey"
            columns: ["resulting_protocol_id"]
            isOneToOne: false
            referencedRelation: "protocols"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_notes: {
        Row: {
          created_at: string
          flagged_red_flag: boolean
          id: string
          mental_health_text: string | null
          mood_level: number | null
          motivation_level: number | null
          note_date: string
          pain_level: number | null
          physical_health_text: string | null
          rom_notes: string | null
          swelling_level: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          flagged_red_flag?: boolean
          id?: string
          mental_health_text?: string | null
          mood_level?: number | null
          motivation_level?: number | null
          note_date: string
          pain_level?: number | null
          physical_health_text?: string | null
          rom_notes?: string | null
          swelling_level?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          flagged_red_flag?: boolean
          id?: string
          mental_health_text?: string | null
          mood_level?: number | null
          motivation_level?: number | null
          note_date?: string
          pain_level?: number | null
          physical_health_text?: string | null
          rom_notes?: string | null
          swelling_level?: string | null
          user_id?: string
        }
        Relationships: []
      }
      daily_plan_entries: {
        Row: {
          dosage_source: string
          exercise_category: string | null
          exercise_name: string
          id: string
          notes: string | null
          plan_date: string
          protocol_phase_id: string
          sort_order: number
          suggested_frequency: string | null
          suggested_reps: number | null
          suggested_sets: number | null
          user_id: string
          user_protocol_selection_id: string
        }
        Insert: {
          dosage_source: string
          exercise_category?: string | null
          exercise_name: string
          id?: string
          notes?: string | null
          plan_date: string
          protocol_phase_id: string
          sort_order?: number
          suggested_frequency?: string | null
          suggested_reps?: number | null
          suggested_sets?: number | null
          user_id: string
          user_protocol_selection_id: string
        }
        Update: {
          dosage_source?: string
          exercise_category?: string | null
          exercise_name?: string
          id?: string
          notes?: string | null
          plan_date?: string
          protocol_phase_id?: string
          sort_order?: number
          suggested_frequency?: string | null
          suggested_reps?: number | null
          suggested_sets?: number | null
          user_id?: string
          user_protocol_selection_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_plan_entries_protocol_phase_id_fkey"
            columns: ["protocol_phase_id"]
            isOneToOne: false
            referencedRelation: "protocol_phases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "daily_plan_entries_user_protocol_selection_id_fkey"
            columns: ["user_protocol_selection_id"]
            isOneToOne: false
            referencedRelation: "user_protocol_selections"
            referencedColumns: ["id"]
          },
        ]
      }
      fit_exports: {
        Row: {
          created_at: string
          export_type: string
          file_path: string
          id: string
          session_log_ids: string[]
          user_id: string
        }
        Insert: {
          created_at?: string
          export_type: string
          file_path: string
          id?: string
          session_log_ids: string[]
          user_id: string
        }
        Update: {
          created_at?: string
          export_type?: string
          file_path?: string
          id?: string
          session_log_ids?: string[]
          user_id?: string
        }
        Relationships: []
      }
      intake_responses: {
        Row: {
          fitness_level: string | null
          id: string
          injury_date: string
          injury_type: string
          lifestyle_notes: string | null
          prior_sports: Json
          protocol_preference: string
          severity: string | null
          side: string
          submitted_at: string
          surgery_date: string | null
          user_id: string
        }
        Insert: {
          fitness_level?: string | null
          id?: string
          injury_date: string
          injury_type: string
          lifestyle_notes?: string | null
          prior_sports?: Json
          protocol_preference: string
          severity?: string | null
          side: string
          submitted_at?: string
          surgery_date?: string | null
          user_id: string
        }
        Update: {
          fitness_level?: string | null
          id?: string
          injury_date?: string
          injury_type?: string
          lifestyle_notes?: string | null
          prior_sports?: Json
          protocol_preference?: string
          severity?: string | null
          side?: string
          submitted_at?: string
          surgery_date?: string | null
          user_id?: string
        }
        Relationships: []
      }
      plan_reviews: {
        Row: {
          acknowledged: boolean
          acknowledged_at: string | null
          created_at: string
          generated_plan_snapshot: Json
          id: string
          reviewer_note: string | null
          user_id: string
          user_protocol_selection_id: string
        }
        Insert: {
          acknowledged?: boolean
          acknowledged_at?: string | null
          created_at?: string
          generated_plan_snapshot: Json
          id?: string
          reviewer_note?: string | null
          user_id: string
          user_protocol_selection_id: string
        }
        Update: {
          acknowledged?: boolean
          acknowledged_at?: string | null
          created_at?: string
          generated_plan_snapshot?: Json
          id?: string
          reviewer_note?: string | null
          user_id?: string
          user_protocol_selection_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "plan_reviews_user_protocol_selection_id_fkey"
            columns: ["user_protocol_selection_id"]
            isOneToOne: false
            referencedRelation: "user_protocol_selections"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          email: string
          id: string
        }
        Insert: {
          created_at?: string
          email: string
          id: string
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
        }
        Relationships: []
      }
      protocol_phases: {
        Row: {
          assistive_devices: Json | null
          continues_from_order_indexes: number[] | null
          criteria_to_discharge: Json | null
          criteria_to_progress: Json | null
          goals: Json
          id: string
          interventions: Json
          name: string | null
          number: number | null
          order_index: number
          protocol_id: string
          timeframe_end_days: number | null
          timeframe_label: string
          timeframe_start_days: number | null
          weight_bearing: Json | null
        }
        Insert: {
          assistive_devices?: Json | null
          continues_from_order_indexes?: number[] | null
          criteria_to_discharge?: Json | null
          criteria_to_progress?: Json | null
          goals?: Json
          id?: string
          interventions?: Json
          name?: string | null
          number?: number | null
          order_index: number
          protocol_id: string
          timeframe_end_days?: number | null
          timeframe_label: string
          timeframe_start_days?: number | null
          weight_bearing?: Json | null
        }
        Update: {
          assistive_devices?: Json | null
          continues_from_order_indexes?: number[] | null
          criteria_to_discharge?: Json | null
          criteria_to_progress?: Json | null
          goals?: Json
          id?: string
          interventions?: Json
          name?: string | null
          number?: number | null
          order_index?: number
          protocol_id?: string
          timeframe_end_days?: number | null
          timeframe_label?: string
          timeframe_start_days?: number | null
          weight_bearing?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "protocol_phases_protocol_id_fkey"
            columns: ["protocol_id"]
            isOneToOne: false
            referencedRelation: "protocols"
            referencedColumns: ["id"]
          },
        ]
      }
      protocols: {
        Row: {
          applies_to: string[]
          created_at: string
          created_by: string | null
          gating: string
          global_notes: Json
          id: string
          is_verified: boolean
          name: string
          raw_json: Json
          red_flags: Json | null
          source: string
          supporting_programs: Json | null
        }
        Insert: {
          applies_to: string[]
          created_at?: string
          created_by?: string | null
          gating: string
          global_notes?: Json
          id: string
          is_verified?: boolean
          name: string
          raw_json: Json
          red_flags?: Json | null
          source: string
          supporting_programs?: Json | null
        }
        Update: {
          applies_to?: string[]
          created_at?: string
          created_by?: string | null
          gating?: string
          global_notes?: Json
          id?: string
          is_verified?: boolean
          name?: string
          raw_json?: Json
          red_flags?: Json | null
          source?: string
          supporting_programs?: Json | null
        }
        Relationships: []
      }
      session_logs: {
        Row: {
          actual_reps: number | null
          actual_sets: number | null
          completed: boolean
          daily_plan_entry_id: string | null
          duration_minutes: number | null
          effort_level: number | null
          id: string
          logged_at: string
          notes: string | null
          pain_level: number | null
          plan_date: string
          user_id: string
        }
        Insert: {
          actual_reps?: number | null
          actual_sets?: number | null
          completed?: boolean
          daily_plan_entry_id?: string | null
          duration_minutes?: number | null
          effort_level?: number | null
          id?: string
          logged_at?: string
          notes?: string | null
          pain_level?: number | null
          plan_date: string
          user_id: string
        }
        Update: {
          actual_reps?: number | null
          actual_sets?: number | null
          completed?: boolean
          daily_plan_entry_id?: string | null
          duration_minutes?: number | null
          effort_level?: number | null
          id?: string
          logged_at?: string
          notes?: string | null
          pain_level?: number | null
          plan_date?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "session_logs_daily_plan_entry_id_fkey"
            columns: ["daily_plan_entry_id"]
            isOneToOne: false
            referencedRelation: "daily_plan_entries"
            referencedColumns: ["id"]
          },
        ]
      }
      user_protocol_selections: {
        Row: {
          anchor_date: string
          created_at: string
          current_phase_order_index: number
          id: string
          protocol_id: string
          status: string
          user_id: string
        }
        Insert: {
          anchor_date: string
          created_at?: string
          current_phase_order_index?: number
          id?: string
          protocol_id: string
          status?: string
          user_id: string
        }
        Update: {
          anchor_date?: string
          created_at?: string
          current_phase_order_index?: number
          id?: string
          protocol_id?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_protocol_selections_protocol_id_fkey"
            columns: ["protocol_id"]
            isOneToOne: false
            referencedRelation: "protocols"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
